#!/bin/bash
# Usage: cropper src.pdf dest.pdf
# Put into same directory of png files to use
if [ $# -ne 2 ]; then
   echo "Usage: $0 src.pdf dest.pdf"
   exit
fi
prog=pngCrop
progName=`dirname $0`/$prog
odirName=`pwd`
dirName=/tmp/pdfCropper
rm -rf $dirName; mkdir $dirName
mudraw -g -o $dirName/page%04d.png $(basename $1)
nParallel=20
jobsDone=0
progress=0
echo Removing empty images...	# < 2kB
find $dirName -type f -size -4b | xargs rm
jobsTot=$(ls $dirName/page*.png | wc -l)
echo -n "Auto-cropping Progress:  0%"
for v in $(ls $dirName/page*.png); do
   while [ $(pgrep $prog | wc -l) -gt $nParallel ]; do
	sleep 0.5s
   done
   eval "$progName $v >/dev/null &"
   ((jobsDone+=1))
   ((tmp=jobsDone*10/jobsTot))
   if [ $tmp -gt $progress ]; then
	progress=$tmp
	printf "\b\b\b%d0%%" $progress
   fi
done
wait
if [ $jobsTot -ne $(ls Opage*.png | wc -l) ]; then
   echo -e "\nOops. Png cropping encountered with some errors."
   echo Removing empty images...
   sleep 0.5s
   find $dirName -type f -size -4b | xargs rm
fi
echo Generating output PDF...
gm convert -compress Bzip -quality 100 $dirName/Opage*.png $odirName/$2
